version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    networks:
      - app-network

  ms-delivery:
    build: .
    container_name: app_delivery
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  mysql-connection:
    image: mysql:5.7.22
    container_name: db_mysql
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
