name: Feature tests

on:
  push:
    branches: ["development", "homolog", "master"]
  pull_request:
    branches: ["development", "homolog", "master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

      db:
        image: mysql:5.7.22
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_PASSWORD: test
          MYSQL_USER: root
        ports:
          - 3388:3306
        volumes:
          - ./mysql/dbdata:/var/lib/mysql

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Copy .env
        run: cp .env.testing .env
      - name: Generate Key
        run: php artisan key:generate
        - name: JWT secret
        run: php artisan jwt:secret
      - name: Create Database
        env:
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: 3306
          DB_DATABASE: test
          DB_USERNAME: test
          DB_PASSWORD: test
      - name: Create Tables
        run: php artisan migrate
      - name: Create Table DiscagemDiretaDistancia
        run: php artisan db:seed --class=DiscagemDiretaDistanciaSeeder
      - name: Create Table Permission
        run: php artisan db:seed --class=PermissionSeeder
      - name: Create Table UnidadeFederativa
        run: php artisan db:seed --class=UnidadeFederativaSeeder
      - name: Optimize
        run: php artisan optimize
      - name: Clear
        run: php artisan config:clear
      - name: Execute tests for create users admin e client
        run: php artisan test --filter=CreateFirstUserTest
      - name: Execute tests feature via PHPUnit
        run: php artisan test tests/Feature