name: Unit tests

on:
  push:
    branches: ["development", "homolog", "master", "a"]
  pull_request:
    branches: ["development", "homolog", "master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - run: composer install
      - run: php artisan key:generate
      - run: chmod -R 777 storage bootstrap/cache
      - run: php artisan test tests/Unit/Services