<?php

namespace App\Support\Enums;

class PermissionEnum
{
    public const CRIAR_CATEGORIA = 'CRIAR CATEGORIA';
    public const CRIAR_FORNECEDOR = 'CRIAR FORNECEDOR';
    public const CRIAR_PAGAMENTO = 'CRIAR PAGAMENTO';
    public const CRIAR_PEDIDO = 'CRIAR PEDIDO';
    public const CRIAR_PRODUTO = 'CRIAR PRODUTO';
    public const EDITAR_CATEGORIA = 'EDITAR CATEGORIA';
    public const EDITAR_ENDERECO = 'EDITAR ENDERECO';
    public const EDITAR_FORNECEDOR = 'EDITAR FORNECEDOR';
    public const EDITAR_PRODUTO = 'EDITAR PRODUTO';
    public const EDITAR_TELEFONE = 'EDITAR TELEFONE';
    public const EDITAR_USUARIO = 'EDITAR USUARIO';
    public const LISTAR_CATEGORIAS = 'LISTAR CATEGORIAS';
    public const LISTAR_FORNECEDORES = 'LISTAR FORNECEDORES';
    public const LISTAR_PEDIDOS = 'LISTAR PEDIDOS';
    public const LISTAR_USUARIOS = 'LISTAR USUARIOS';
    public const LISTAR_DETALHES_CATEGORIA = 'LISTAR DETALHES DA CATEGORIA';
    public const LISTAR_DETALHES_FORNECEDOR = 'LISTAR DETALHES DO FORNECEDOR';
    public const LISTAR_DETALHES_PEDIDO = 'LISTAR DETALHES DO PEDIDO';    
    public const LISTAR_DETALHES_USUARIO = 'LISTAR DETALHES DO USUARIO';
}
