<?php

namespace App\Support\Enums;

enum PermissionEnum: string
{
    const CRIAR_CATEGORIA = 'CRIAR CATEGORIA';
    const CRIAR_FORNECEDOR = 'CRIAR FORNECEDOR';
    const CRIAR_PAGAMENTO = 'CRIAR PAGAMENTO';
    const CRIAR_PEDIDO = 'CRIAR PEDIDO';
    const CRIAR_PRODUTO = 'CRIAR PRODUTO';
    const EDITAR_CATEGORIA = 'EDITAR CATEGORIA';
    const EDITAR_ENDERECO = 'EDITAR ENDERECO';
    const EDITAR_FORNECEDOR = 'EDITAR FORNECEDOR';
    const EDITAR_PRODUTO = 'EDITAR PRODUTO';
    const EDITAR_TELEFONE = 'EDITAR TELEFONE';
    const EDITAR_USUARIO = 'EDITAR USUARIO';
    const LISTAR_CATEGORIAS = 'LISTAR CATEGORIAS';
    const LISTAR_FORNECEDORES = 'LISTAR FORNECEDORES';
    const LISTAR_PEDIDOS = 'LISTAR PEDIDOS';
    const LISTAR_USUARIOS = 'LISTAR USUARIOS';
    const LISTAR_DETALHES_CATEGORIA = 'LISTAR DETALHES DA CATEGORIA';
    const LISTAR_DETALHES_FORNECEDOR = 'LISTAR DETALHES DO FORNECEDOR';
    const LISTAR_DETALHES_PEDIDO = 'LISTAR DETALHES DO PEDIDO';    
    const LISTAR_DETALHES_USUARIO = 'LISTAR DETALHES DO USUARIO';
}
