<?php

namespace App\Support\Enums;

class PermissionEnum
{
    public const CRIAR_ENDERECO = 'CRIAR ENDEREÇO';
    public const LISTAR_UFS = 'LISTAR UFS';
    public const EDITAR_ENDERECO = 'EDITAR ENDEREÇO';
    public const HABILITAR_DESABILITAR_ENDERECO = 'HABILITAR/DESABILITAR ENDEREÇO';
    public const CRIAR_CATEGORIA = 'CRIAR CATEGORIA';
    public const LISTAR_CATEGORIAS = 'LISTAR CATEGORIAS';
    public const LISTAR_DETALHES_CATEGORIA = 'LISTAR DETALHES DA CATEGORIA';
    public const EDITAR_CATEGORIA = 'EDITAR CATEGORIA';
    public const HABILITAR_DESABILITAR_CATEGORIA = 'HABILITAR/DESABILITAR CATEGORIA';
    public const CRIAR_PEDIDO = 'CRIAR PEDIDO';
    public const LISTAR_PEDIDOS = 'LISTAR PEDIDOS';
    public const LISTAR_DETALHES_PEDIDO = 'LISTAR DETALHES DO PEDIDO';
    public const HABILITAR_DESABILITAR_PEDIDO = 'HABILITAR/DESABILITAR PEDIDO';
    public const CRIAR_PAGAMENTO = 'CRIAR PAGAMENTO';
    public const CRIAR_PRODUTO = 'CRIAR PRODUTO';
    public const LISTAR_PRODUTOS = 'LISTAR PRODUTOS';
    public const LISTAR_DETALHES_PRODUTO = 'LISTAR DETALHES DO PRODUTO';
    public const EDITAR_PRODUTO = 'EDITAR PRODUTO';
    public const HABILITAR_DESABILITAR_PRODUTO = 'HABILITAR/DESABILITAR PRODUTO';
    public const CRIAR_FORNECEDOR = 'CRIAR FORNECEDOR';
    public const LISTAR_FORNECEDORES = 'LISTAR FORNECEDORES';
    public const LISTAR_DETALHES_FORNECEDOR = 'LISTAR DETALHES DO FORNECEDOR';
    public const EDITAR_FORNECEDOR = 'EDITAR FORNECEDOR';
    public const HABILITAR_DESABILITAR_FORNECEDOR = 'HABILITAR/DESABILITAR FORNECEDOR';
    public const CRIAR_TELEFONE = 'CRIAR TELEFONE';
    public const LISTAR_DDDS = 'LISTAR DDDS';
    public const EDITAR_TELEFONE = 'EDITAR TELEFONE';
    public const HABILITAR_DESABILITAR_TELEFONE = 'HABILITAR/DESABILITAR TELEFONE';
    public const CRIAR_USUARIO = 'CRIAR USUARIO';
    public const LISTAR_USUARIOS = 'LISTAR USUARIOS';
    public const LISTAR_DETALHES_USUARIO = 'LISTAR DETALHES DO USUARIO';
    public const EDITAR_USUARIO = 'EDITAR USUARIO';
    public const HABILITAR_DESABILITAR_USUARIO = 'HABILITAR/DESABILITAR USUARIO';
}
