name: Laravel Tests

on:
  push:
    branches:
      - development
      - homolog
      - master
  pull_request:
    branches:
      - development
      - homolog
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

      db:
        image: mysql:5.7.22
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_PASSWORD: test
          MYSQL_USER: root
        ports:
          - 3388:3306
        volumes:
          - ./.docker/mysql/dbdata:/var/lib/mysql

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Copy .env
        run: cp .env.testing .env

      - name: Generate Key
        run: php artisan key:generate

      - name: JWT secret
        run: php artisan jwt:secret

      - name: Create Database
        run: |
          php artisan config:cache
          php artisan migrate --force

      - name: Create Tables
        run: |
          php artisan db:seed --class=DiscagemDiretaDistanciaSeeder
          php artisan db:seed --class=PermissionSeeder
          php artisan db:seed --class=UnidadeFederativaSeeder

      - name: Optimize
        run: php artisan optimize

      - name: Execute Tests
        run: php artisan test
